version: 'V0.8.4'
icon_path: 'config/th.jpg'
template_path: 'templates/report_template.docx'
vulnerabilities_file: 'data/vulnerabilities.xlsx'
icp_info_file: 'data/icp_info.xlsx'
supplierName: '张三'
city: '北京'
unitType:
  - 民营企业
  - 事业单位
  - 国有企业
  - 社会团体
  - 民办非企业
  - 人大政协
  - 党委机关
  - 政府机关
  - 其他组织
  - 
industry:
  - 
  - 科技
  - 政府
  - 广电
  - 税务
  - 能源
  - 电信
  - 财政
  - 宣传
  - 应急管理
  - 金融
  - 交通
  - 卫健
  - 教育
  - 发改
  - 人社
  - 环保
  - 质量监督
  - 烟草
  - 邮政
  - 工商
  - 民政
  - 住建
  - 民委
  - 公检法
  - 电子商务
  - 民航
  - 文旅
  - 工信
  - 统计
  - 外交
  - 审计
  - 农林水
  - 国土资源
  - 证券
  - 气象
  - 国资
  - 物流
  - 地震
  - 食药监
  - 知识产权
  - 航天
  - 海关
  - 保险
  - 海洋
  - 档案
  - 商务
  - 民生企业
