version: 'V0.6.2'
supplierName: '张三'
city: '郑州'
unitType:
  - 民营企业
  - 事业单位
  - 国有企业
  - 社会团体
  - 民办非企业
  - 人大政协
  - 党委机关
  - 政府机关
  - 其他组织
  - 
industry:
  - 
  - 科技
  - 政府
  - 广电
  - 税务
  - 能源
  - 电信
  - 财政
  - 宣传
  - 应急管理
  - 金融
  - 交通
  - 卫健
  - 教育
  - 发改
  - 人社
  - 环保
  - 质量监督
  - 烟草
  - 邮政
  - 工商
  - 民政
  - 住建
  - 民委
  - 公检法
  - 电子商务
  - 民航
  - 文旅
  - 工信
  - 统计
  - 外交
  - 审计
  - 农林水
  - 国土资源
  - 证券
  - 气象
  - 国资
  - 物流
  - 地震
  - 食药监
  - 知识产权
  - 航天
  - 海关
  - 保险
  - 海洋
  - 档案
  - 商务
  - 民生企业
vulnerabilities:
  弱口令: '1.使用多种字符组合的强密码，如大小写字母+数字+特殊字符。

    2.用户密码中不要出现与用户名或者系统名相关的字符。'

  敏感信息泄露: 
    1、在服务器端对相关敏感信息进行模糊化处理。

    2、对服务器端返回的数据进行严格的检查，满足查询数据与页面显示数据一致。
  
  日志泄露: 
    1、在服务器端对相关敏感信息进行模糊化处理。

    2、对服务器端返回的数据进行严格的检查，满足查询数据与页面显示数据一致。

  SQL注入: 对系统前端输入加以校验，对数据库查询语句加以限制，增加过滤字段，以确保拦截SQL注入关键字。

  未授权访问: 
    1、页面进行严格的访问权限的控制以及对访问角色进行权限检查。
    
    2、可以使用 session 对用户的身份进行判断和控制。

  列目录: 
    1、通过修改配置文件，禁止中间件（如 IIS、apache、tomcat）的文件目录索引功能。

    2、设置目录访问权限。

  权限认证绕过: 页面进行严格的访问权限的控制以及对访问角色进行权限检查。

  文件上传: 
    1、严格限制和校验上传的文件，禁止上传恶意代码的文件。同时限制相关上传文件目录的执行权限，防止木马执行。

    2、对上传文件格式进行严格校验，防止上传恶意脚本文件。

  验证码重复利用: 
    1.禁止前端校验或者无效校验。

    2.验证码和用户名、密码需要一次性、同时提交给服务器验证，以此来保持业务一致性。

  任意文件下载: 对传入的文件名参数进行过滤，并且判断是否是允许获取的文件类型，过滤回溯符../。

  命令执行: 
    1、严格过滤用户输入的数据，禁止执行非预期系统命令。
    
    2、客户端提交的变量在放入函数前进行检测。

  代码执行:
    1、严格过滤用户输入的数据，禁止执行非预期系统命令。

    2、减少或不使用代码或命令执行函数

    3、客户端提交的变量在放入函数前进行检测

    4、减少或不使用危险函数

  短信轰炸: 在服务器限制发送短信或邮件的频率，如同一账号 1 分钟只能发送 1 次短信或邮件，一天只能发送 3 次。

  ssrf: 
    1、禁用不需要的协议，只允许 HTTP 和 HTTPS 请求，可以防止类似于 file://, gopher://, ftp:// 等引起的问题。

    2、白名单的方式限制访问的目标地址，禁止对内网发起请求

  xss: 
    1、过滤输入的数据，对例如：“‘”，“ “ ”，” < “，” > “，” on* “，script、iframe 等危险字符进行严格的检查。
    
    2、对输出到页面的数据进行相应的编码转换，如 HTML 实体编码、JS 编码等。
